### ISSUE TITLE
function clause match error in `Sourceror.Comments.do_extract_comments/4`

### ISSUE THREAD

**Issue by zachdaniel** [doorgan/sourceror#150]
This is from a freshly generated phoenix project. Parsing and stringifying this file raises an error:

```elixir
import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :foobar, FoobarWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Foobar.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
```

error

```elixir
** (FunctionClauseError) no function clause matching in Sourceror.Comments.do_extract_comments/4

    The following arguments were given to Sourceror.Comments.do_extract_comments/4:

        # 1
        {:__block__,
         [
           end_of_expression: [line: 21],
           __sourceror__: %{trailing_block: true},
           trailing_comments: [
             %{
               line: 19,
               text: "# Runtime production configuration, including reading",
               column: 1,
               next_eol_count: 1,
               previous_eol_count: 2
             },
             %{
               line: 20,
               text: "# of environment variables, is done on config/runtime.exs.",
               column: 1,
               next_eol_count: 1,
               previous_eol_count: 1
             }
           ],
           leading_comments: [],
           line: 17
         ],
         [
           {:config,
            [
              end_of_expression: [line: 17, newlines: 1, column: 29],
              trailing_comments: [],
              leading_comments: [
                %{
                  line: 16,
                  text: "# Do not print debug messages in production",
                  column: 1,
                  next_eol_count: 1,
                  previous_eol_count: 2
                }
              ],
              line: 17,
              column: 1
            ],
            [
              {:__block__,
               [trailing_comments: [], leading_comments: [], line: 17, column: 8],
               [:logger]},
              [
                {{:__block__,
                  [
                    trailing_comments: [],
                    leading_comments: [],
                    format: :keyword,
                    line: 17,
                    column: 17
                  ], [:level]},
                 {:__block__,
                  [trailing_comments: [], leading_comments: [], line: 17, column: 24],
                  [:info]}}
              ]
            ]}
         ]}

        # 2
        [
          %{
            line: 3,
            text: "# Note we also include the path to a cache manifest",
            column: 1,
            next_eol_count: 1,
            previous_eol_count: 2
          },
          %{
            line: 4,
            text: "# containing the digested version of static files. This",
            column: 1,
            next_eol_count: 1,
            previous_eol_count: 1
          },
          %{
            line: 5,
            text: "# manifest is generated by the `mix assets.deploy` task,",
            column: 1,
            next_eol_count: 1,
            previous_eol_count: 1
          },
          %{
            line: 6,
            text: "# which you should run after static files are built and",
            column: 1,
            next_eol_count: 1,
            previous_eol_count: 1
          },
          %{
            line: 7,
            text: "# before starting your production server.",
            column: 1,
            next_eol_count: 1,
            previous_eol_count: 1
          },
          %{
            line: 10,
            text: "# Configures Swoosh API Client",
            column: 1,
            next_eol_count: 1,
            previous_eol_count: 2
          },
          %{
            line: 13,
            text: "# Disable Swoosh Local Memory Storage",
            column: 1,
            next_eol_count: 1,
            previous_eol_count: 2
          }
        ]

        # 3
        true

        # 4
        true

    Attempted function clauses (showing 2 out of 2):

        defp do_extract_comments({_, meta, [quoted]}, [], collapse_comments, true)
        defp do_extract_comments({_, meta, _} = quoted, acc, collapse_comments, false)

    (sourceror 1.3.0) lib/sourceror/comments.ex:154: Sourceror.Comments.do_extract_comments/4
    (elixir 1.17.0) lib/macro.ex:639: anonymous fn/4 in Macro.do_traverse_args/4
    (stdlib 6.0) lists.erl:2343: :lists.mapfoldl_1/3
    (stdlib 6.0) lists.erl:2344: :lists.mapfoldl_1/3
    (elixir 1.17.0) lib/macro.ex:604: Macro.do_traverse/4
    (sourceror 1.3.0) lib/sourceror.ex:263: Sourceror.to_algebra/2
    (sourceror 1.3.0) lib/sourceror.ex:236: Sourceror.to_string/2
    iex:4: (file)
```

To reproduce, you can parse and stringily that code I posted.

**Comment by doorgan** [comment]
Fixed in #151
